version: "2"
services:
  node:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    restart: always
    logging:
        options:
            max-size: '10m'
            max-file: '10'
        driver: json-file
    links:
      - redis
  redis:
    image: "redis:latest"
    volumes:
      - ./redis:/data
    restart: always
